# this docker-compose runs a single node kafka for dev enviromnent

version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "judgeRequest:3:1,judgeResponse:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  kafka2:
#   image: wurstmeister/kafka
#   ports:
#     - "9093:9092"
#   environment:
#     KAFKA_ADVERTISED_HOST_NAME: localhost
#     KAFKA_CREATE_TOPICS: "judgeRequest:3:1,judgeResponse:3:1"
#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#  kafka3:
#    image: wurstmeister/kafka
#    ports:
#      - "9094:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_CREATE_TOPICS: "judgeRequest:3:1,judgeResponse:3:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
