apiVersion: apps/v1
kind: Deployment
metadata:
  name: judger-deployment
spec:
  selector:
    matchLabels:
      app: judger
  replicas: 2
  template:
    metadata:
      labels:
        app: judger
    spec:
      containers:
        - name: judger
          image: rabbitoj:latest
          imagePullPolicy: Always
          env:
            - name: Role
              value: "Judge"
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: "/var/run/docker.sock"