// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JudgeRequest struct {
	Sid                  uint32   `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tid                  uint32   `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	TidVersion           uint32   `protobuf:"varint,3,opt,name=tid_version,json=tidVersion,proto3" json:"tid_version,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{0}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *JudgeRequest) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *JudgeRequest) GetTidVersion() uint32 {
	if m != nil {
		return m.TidVersion
	}
	return 0
}

func (m *JudgeRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *JudgeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type JudgeResponse struct {
	Sid                  uint32   `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Stdout               string   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{1}
}

func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (m *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(m, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

func (m *JudgeResponse) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *JudgeResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

type Case struct {
	Stdin                string   `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout               string   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{2}
}

func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (m *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(m, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetStdin() string {
	if m != nil {
		return m.Stdin
	}
	return ""
}

func (m *Case) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

type TestCaseRequest struct {
	Tid                  uint32   `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCaseRequest) Reset()         { *m = TestCaseRequest{} }
func (m *TestCaseRequest) String() string { return proto.CompactTextString(m) }
func (*TestCaseRequest) ProtoMessage()    {}
func (*TestCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{3}
}

func (m *TestCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseRequest.Unmarshal(m, b)
}
func (m *TestCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseRequest.Marshal(b, m, deterministic)
}
func (m *TestCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseRequest.Merge(m, src)
}
func (m *TestCaseRequest) XXX_Size() int {
	return xxx_messageInfo_TestCaseRequest.Size(m)
}
func (m *TestCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseRequest proto.InternalMessageInfo

func (m *TestCaseRequest) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type TestCaseResponse struct {
	Tid                  uint32   `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Case                 []*Case  `protobuf:"bytes,2,rep,name=case,proto3" json:"case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCaseResponse) Reset()         { *m = TestCaseResponse{} }
func (m *TestCaseResponse) String() string { return proto.CompactTextString(m) }
func (*TestCaseResponse) ProtoMessage()    {}
func (*TestCaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{4}
}

func (m *TestCaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseResponse.Unmarshal(m, b)
}
func (m *TestCaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseResponse.Marshal(b, m, deterministic)
}
func (m *TestCaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseResponse.Merge(m, src)
}
func (m *TestCaseResponse) XXX_Size() int {
	return xxx_messageInfo_TestCaseResponse.Size(m)
}
func (m *TestCaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseResponse proto.InternalMessageInfo

func (m *TestCaseResponse) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *TestCaseResponse) GetCase() []*Case {
	if m != nil {
		return m.Case
	}
	return nil
}

func init() {
	proto.RegisterType((*JudgeRequest)(nil), "proto.JudgeRequest")
	proto.RegisterType((*JudgeResponse)(nil), "proto.JudgeResponse")
	proto.RegisterType((*Case)(nil), "proto.Case")
	proto.RegisterType((*TestCaseRequest)(nil), "proto.TestCaseRequest")
	proto.RegisterType((*TestCaseResponse)(nil), "proto.TestCaseResponse")
}

func init() { proto.RegisterFile("judge.proto", fileDescriptor_a2b4fa635fb2baaa) }

var fileDescriptor_a2b4fa635fb2baaa = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0x53, 0x68, 0x09, 0x4c, 0xbf, 0x7c, 0x25, 0x23, 0xc1, 0x4d, 0x2f, 0x34, 0xf5, 0xd2,
	0x13, 0x87, 0xea, 0xc5, 0x98, 0x78, 0x51, 0x43, 0xc2, 0xb1, 0x31, 0x5e, 0x4d, 0x65, 0x27, 0xcd,
	0x1a, 0xd2, 0x45, 0x76, 0xea, 0x3f, 0xe0, 0x3f, 0x6e, 0xba, 0x5b, 0x28, 0xf8, 0xe3, 0xd4, 0x7d,
	0x9f, 0x9d, 0xd7, 0x79, 0xaf, 0x85, 0xf0, 0xad, 0x96, 0x25, 0x2d, 0xb6, 0x3b, 0xcd, 0x1a, 0x03,
	0xfb, 0x48, 0x3e, 0x3d, 0xf8, 0xb7, 0x6a, 0x70, 0x4e, 0xef, 0x35, 0x19, 0xc6, 0x09, 0xf4, 0x8d,
	0x92, 0xc2, 0x8b, 0xbd, 0x74, 0x9c, 0x37, 0xc7, 0x86, 0xb0, 0x92, 0xa2, 0xe7, 0x08, 0x2b, 0x89,
	0x73, 0x08, 0x59, 0xc9, 0x97, 0x0f, 0xda, 0x19, 0xa5, 0x2b, 0xd1, 0xb7, 0x37, 0xc0, 0x4a, 0x3e,
	0x3b, 0x82, 0x11, 0x0c, 0x37, 0x45, 0x55, 0xd6, 0x45, 0x49, 0xc2, 0x8f, 0xbd, 0x74, 0x94, 0x1f,
	0x34, 0x22, 0xf8, 0x6b, 0x2d, 0x49, 0x04, 0x96, 0xdb, 0x73, 0x72, 0x03, 0xe3, 0x36, 0x84, 0xd9,
	0xea, 0xca, 0xd0, 0x2f, 0x29, 0x66, 0x30, 0x30, 0x2c, 0x75, 0xcd, 0x36, 0xc8, 0x28, 0x6f, 0x55,
	0x72, 0x0d, 0xfe, 0x7d, 0x61, 0x08, 0xa7, 0x10, 0x18, 0x96, 0xaa, 0xb2, 0x9e, 0x51, 0xee, 0xc4,
	0x9f, 0xae, 0x4b, 0x38, 0x7b, 0x22, 0xc3, 0x8d, 0xf3, 0xa8, 0x38, 0x77, 0x2b, 0x59, 0xc9, 0xe4,
	0x11, 0x26, 0xdd, 0x50, 0x17, 0xec, 0x74, 0x0a, 0xe7, 0xe0, 0xaf, 0x0b, 0x43, 0xa2, 0x17, 0xf7,
	0xd3, 0x30, 0x0b, 0xdd, 0xe7, 0x5d, 0x58, 0x93, 0xbd, 0xc8, 0x1e, 0x20, 0xb0, 0xe5, 0xf0, 0x16,
	0xfe, 0x2f, 0x89, 0xf7, 0x45, 0xeb, 0x0d, 0xe3, 0x79, 0x3b, 0x7d, 0xfc, 0x07, 0xa2, 0xe9, 0x29,
	0x74, 0x8b, 0xb3, 0x15, 0x0c, 0xf7, 0x61, 0xf0, 0x0e, 0xc2, 0x25, 0xf1, 0x41, 0xce, 0x5a, 0xc3,
	0xb7, 0x46, 0xd1, 0xc5, 0x0f, 0xee, 0xde, 0xf5, 0x3a, 0xb0, 0xfc, 0xea, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0xdd, 0xd3, 0x84, 0x26, 0x11, 0x02, 0x00, 0x00,
}
