// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/protobuf/case.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Case struct {
	Stdin                []byte   `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout               []byte   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Case) Reset()         { *m = Case{} }
func (m *Case) String() string { return proto.CompactTextString(m) }
func (*Case) ProtoMessage()    {}
func (*Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b8b32ff2e63a1d2, []int{0}
}

func (m *Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Case.Unmarshal(m, b)
}
func (m *Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Case.Marshal(b, m, deterministic)
}
func (m *Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Case.Merge(m, src)
}
func (m *Case) XXX_Size() int {
	return xxx_messageInfo_Case.Size(m)
}
func (m *Case) XXX_DiscardUnknown() {
	xxx_messageInfo_Case.DiscardUnknown(m)
}

var xxx_messageInfo_Case proto.InternalMessageInfo

func (m *Case) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *Case) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

type TestCaseRequest struct {
	Tid                  uint32   `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCaseRequest) Reset()         { *m = TestCaseRequest{} }
func (m *TestCaseRequest) String() string { return proto.CompactTextString(m) }
func (*TestCaseRequest) ProtoMessage()    {}
func (*TestCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b8b32ff2e63a1d2, []int{1}
}

func (m *TestCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseRequest.Unmarshal(m, b)
}
func (m *TestCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseRequest.Marshal(b, m, deterministic)
}
func (m *TestCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseRequest.Merge(m, src)
}
func (m *TestCaseRequest) XXX_Size() int {
	return xxx_messageInfo_TestCaseRequest.Size(m)
}
func (m *TestCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseRequest proto.InternalMessageInfo

func (m *TestCaseRequest) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type TestCaseResponse struct {
	Tid                  uint32   `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Case                 []*Case  `protobuf:"bytes,2,rep,name=case,proto3" json:"case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCaseResponse) Reset()         { *m = TestCaseResponse{} }
func (m *TestCaseResponse) String() string { return proto.CompactTextString(m) }
func (*TestCaseResponse) ProtoMessage()    {}
func (*TestCaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b8b32ff2e63a1d2, []int{2}
}

func (m *TestCaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseResponse.Unmarshal(m, b)
}
func (m *TestCaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseResponse.Marshal(b, m, deterministic)
}
func (m *TestCaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseResponse.Merge(m, src)
}
func (m *TestCaseResponse) XXX_Size() int {
	return xxx_messageInfo_TestCaseResponse.Size(m)
}
func (m *TestCaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseResponse proto.InternalMessageInfo

func (m *TestCaseResponse) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *TestCaseResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TestCaseResponse) GetCase() []*Case {
	if m != nil {
		return m.Case
	}
	return nil
}

func init() {
	proto.RegisterType((*Case)(nil), "protobuf.Case")
	proto.RegisterType((*TestCaseRequest)(nil), "protobuf.TestCaseRequest")
	proto.RegisterType((*TestCaseResponse)(nil), "protobuf.TestCaseResponse")
}

func init() { proto.RegisterFile("models/protobuf/case.proto", fileDescriptor_7b8b32ff2e63a1d2) }

var fileDescriptor_7b8b32ff2e63a1d2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xdd, 0x4a, 0x86, 0x40,
	0x10, 0x86, 0xf1, 0x27, 0xb3, 0xb1, 0x1f, 0x59, 0x22, 0x36, 0x8f, 0x64, 0x3b, 0xf1, 0x48, 0xc1,
	0xba, 0x83, 0x82, 0x4e, 0x63, 0xe9, 0x06, 0xb4, 0x9d, 0x40, 0x28, 0xd7, 0x9c, 0xb1, 0xeb, 0x0f,
	0xd7, 0x36, 0xa1, 0xef, 0x3b, 0xdb, 0x67, 0xde, 0x79, 0x77, 0x1e, 0x28, 0x3e, 0xad, 0xc1, 0x0f,
	0x6a, 0xa6, 0xd9, 0xb2, 0xed, 0x97, 0xf7, 0xe6, 0xad, 0x23, 0xac, 0x1d, 0x89, 0xd4, 0x0f, 0xd5,
	0x03, 0xc4, 0x8f, 0x1d, 0xa1, 0xb8, 0x86, 0x13, 0x62, 0x33, 0x8c, 0x32, 0x28, 0x83, 0xea, 0x5c,
	0x6f, 0x20, 0x6e, 0x20, 0x21, 0x36, 0x76, 0x61, 0x19, 0xba, 0xf1, 0x2f, 0xa9, 0x3b, 0xb8, 0x7a,
	0x45, 0xe2, 0xb5, 0xa9, 0xf1, 0x6b, 0x41, 0x62, 0x91, 0x43, 0xc4, 0x83, 0x71, 0xf5, 0x0b, 0xbd,
	0x3e, 0x55, 0x0f, 0xf9, 0xbe, 0x44, 0x93, 0x1d, 0x09, 0x0f, 0xb7, 0x84, 0x84, 0xd3, 0x6f, 0x9c,
	0x69, 0xb0, 0xa3, 0x8c, 0xca, 0xa0, 0x3a, 0xd3, 0x1e, 0x85, 0x82, 0x78, 0x55, 0x96, 0x61, 0x19,
	0x55, 0x59, 0x7b, 0x59, 0x7b, 0xe7, 0xda, 0xfd, 0xe8, 0xb2, 0xf6, 0x05, 0x52, 0x7f, 0x43, 0x3c,
	0x41, 0xf6, 0x8c, 0xfc, 0x87, 0xb7, 0x7b, 0xe1, 0x9f, 0x6b, 0x51, 0x1c, 0x8b, 0x36, 0xc3, 0x3e,
	0x71, 0xd1, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x05, 0x4d, 0x59, 0x3f, 0x01, 0x00,
	0x00,
}
